"""add gender to person

Revision ID: 12f18d2137eb
Revises: bbc3bd0546bb
Create Date: 2020-10-21 01:46:47.855453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f18d2137eb'
down_revision = 'bbc3bd0546bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('gender', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'gender')
    # ### end Alembic commands ###
