"""Add Person

Revision ID: 44df7c2b4a5c
Revises: 
Create Date: 2020-10-20 15:56:54.526844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44df7c2b4a5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
